# action.yml
name: 'Veracode Static Analysis Pipeline Scan and SARIF import'
description: 'Initiate a Veracode Static Analysis Pipeline Scan and convert the results file to a valid SARIF file'
inputs:
  pipeline-results-json:  # id of input
    description: 'location of the pipeline json result file'
    required: true
    default: 'results.json'
  output-results-sarif:  # id of input
    description: 'the path to the SARIF file as an output of the transformation'
    required: true
    default: 'veracode-results.sarif'  
  source-base-path-1:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  source-base-path-2:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  source-base-path-3:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  finding-rule-level:
    description: 'The conversion rule of Veracode findings to GitHub level'
    required: true
    default: '4:3:0'
runs:
  using: 'node16'
  main: 'dist/index.js'
